# Array

## Array Creation 

In [19]:
# using the array module 
import sys 
import array 
arr = array.array('i', [1,2,4,5,6,7,10])
print(arr)
print(type(arr))
print(sys.getsizeof(arr))

array('i', [1, 2, 4, 5, 6, 7, 10])
<class 'array.array'>
108


In [26]:
# Using a list 
arr = [1,2,3,4,5,10]
print(arr)
print(type(arr))
print(sys.getsizeof(arr))


[1, 2, 3, 4, 5, 10]
<class 'list'>
104


In [30]:
# array using numpy 
import numpy as np 
arr = np.array([12,3,4,5,6])
print(arr)
print(type(arr))
print(sys.getsizeof(arr))

[12  3  4  5  6]
<class 'numpy.ndarray'>
132


## Slicing in 1D array

In [21]:
# Slicing 
# in slicing indexing start from 0
arr = [10, 20, 30, 40, 50, 60]

print(arr[-3:-1]) # Output: [40, 50]
print(arr[::-1])#array[start:stop:step] #Reverse an Array
print(arr[::2])#Extract Even Index Elements
print(arr[1::2])#Extract Odd Index Elements
print(arr[-3:])# Extract last 3 elements 
print(arr[::-2])# Extract Alternate elements in reverse order 

[40, 50]
[60, 50, 40, 30, 20, 10]
[10, 30, 50]
[20, 40, 60]
[40, 50, 60]
[60, 40, 20]


# Insertion in 1D array

In [13]:
#The existing elements are shifted to the right to make space for the new element.
arr = [1, 2, 3, 5]
arr.insert(3,10)  # Insert 4 at index 3
print(arr)  # Output: [1, 2, 3, 4, 5]

[1, 2, 3, 10, 5]


In [19]:
# insertion using numpy 
#np.insert(array, index, values): Inserts values at the given index
import numpy as np 
arr = np.array([3,4,5,6,7,8])
arr = np.insert(arr,4,12)
print(arr)

[ 3  4  5  6 12  7  8]


## Append in 1D array 

In [9]:
# append
#Adds an element to the end of the list
#
arr = [1, 2, 3, 5]
arr.append(10)# list.append() takes only one element 
print(arr)

[1, 2, 3, 5, 10]


In [21]:
#np.append(array, values): Appends values to the array
arr = np.array([1, 2, 3])
arr = np.append(arr,(4,5,6))
print(arr)

[1 2 3 4 5 6]


### Note 

In [81]:
# Python lists: append() and insert() modify the original list.
# NumPy arrays: np.append() and np.insert() return a new array without modifying the original one.

## Concatenate() in np.array

In [27]:
arr1 = np.array([1, 2, 3]) #  Used for merging multiple arrays
arr2 = np.array([4, 5])
new_arr = np.concatenate((arr1, arr2))
new_arr2 = np.concatenate((arr2,arr1))
print(new_arr)  # Output: [1 2 3 4 5]
print(new_arr2)

[1 2 3 4 5]
[4 5 1 2 3]


##  (Extend  & + operator) used in python list for merge two list 
## Concatinate not work with list 

In [29]:
arr1  = [1, 2, 3]
arr2 = [4, 5]
arr3 = concatenate(arr1, arr2)

NameError: name 'concatenate' is not defined

In [92]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
result = list1 + list2
print(result)  # Output: [1, 2, 3, 4, 5, 6]


[1, 2, 3, 4, 5, 6]


In [94]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
list1.extend(list2)
print(list1)  # Output: [1, 2, 3, 4, 5, 6]


[1, 2, 3, 4, 5, 6]


## Using np.hstack() (Horizontal Stack)

In [35]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5])
new_arr = np.hstack((arr1, arr2))

print(new_arr)  # Output: [1 2 3 4 5]


[1 2 3 4 5]


## Using np.resize() (Resizing the array)

In [37]:
arr = np.array([1, 2, 3])
new_arr = np.resize(arr, (6,))
new_arr[2:5] = [4, 5, 6]
print(new_arr)  # Output: [1 2 3 4 5 6]


[1 2 4 5 6 3]


In [41]:
arr = np.array([1, 2, 3])
new_arr = np.resize(arr, (6,))
print(new_arr)
print(arr)
arr.resize((6,))
print(arr)


[1 2 3 1 2 3]
[1 2 3]
[1 2 3 0 0 0]


In [102]:
arr = np.array([1, 2, 3, 4, 5, 6])
resized_arr = np.resize(arr, (3, 2))  # (rows, columns)
print(resized_arr)

[[1 2]
 [3 4]
 [5 6]]


# Deleteion of elements in an 1D array 

## del in python list 


In [125]:
# Deletes an element at a specific index or deletes the entire list
list = [1, 2, 3, 4]
del list[1]  # Deletes element at index 1
print(list)  # Output: [1, 3, 4]

del list  # Deletes the entire list
print(list)

[1, 3, 4]
<class 'list'>


## Remove in python list 

In [132]:
#Removes the first occurrence of a specific element.
lst = [1, 2, 3, 4,3,3]
lst.remove(3)  # Removes the first occurrence of 3
print(lst)  # Output: [1, 2, 4]

[1, 2, 4, 3, 3]


## pop in python list 

In [136]:
lst = [1, 2, 3, 4]
lst.pop(2)  # Removes and returns element at index 2
print(lst)  # Output: [1, 2, 4]

lst.pop()  # Removes the last element
print(lst)  # Output: [1, 2]


[1, 2, 4]
[1, 2]


## clear() method in python list 

In [139]:
#Removes all elements from the list, making it empty.
lst = [1, 2, 3, 4]
lst.clear()
print(lst)  # Output: []

[]


## np.delete() in NumPy arrays 

In [142]:
#Deletes elements from an array at a specific index or condition.
arr = np.array([1,2,3,4])
new_arr = np.delete(arr,1) # delete element at index 1 
print(new_arr)


[1 3 4]


In [152]:
#np.delete() with Axis
arr = np.array([[1, 2], [3, 4], [5, 6]])
new_arr = np.delete(arr,1,axis=1)
print(new_arr)

[[1]
 [3]
 [5]]


In [43]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
new_arr = np.delete(arr,1,axis=0)
print(new_arr)

[[1 2]
 [5 6]]


## Using Boolean Masking 

In [59]:
#Use a boolean condition to remove elements that satisfy a certain condition
arr = np.array([1,3,5,6,3,6])
new_arr = arr[arr!= 3]
new_arr2 = arr[arr==6]
print(new_arr)
print(new_arr2)

[1 5 6 6]
[6 6]


## np.resize() 

In [148]:
# Resizes the array and removes extra elements if the new size is smaller
arr = np.array([2,3,5,6,4,8,10])
new_arr = np.resize(arr,(3,))
print(new_arr)

[2 3 5]


# loop through an array

In [159]:
arr = [10, 20, 30, 40]
for num in arr:
    print(num)


10
20
30
40


In [167]:
arr = [10, 20, 30, 40]
i = 0 
while i<len(arr): 
    print(arr[i])
    i+=1

10
20
30
40


# reverse an array 

## Using reverse() in python list 

In [172]:
arr = [1, 2, 3, 4, 5]
arr.reverse()
print(arr)

[5, 4, 3, 2, 1]


## Using Slicing in python list 

In [176]:
arr = arr[::-1]
print(arr)

[5, 4, 3, 2, 1]


## np.flip method in NumPy

In [185]:
arr = np.array([1, 2, 3, 4, 5])
new_arr = np.flip(arr)
print(new_arr)
print(arr)

[5 4 3 2 1]
[1 2 3 4 5]


# Sort Array 

## sort in list 

In [189]:
arr = [3, 1, 4, 1, 5, 9, 2, 6]
arr.sort()
print(arr)  # Output: [1, 1, 2, 3, 4, 5, 6, 9]


[1, 1, 2, 3, 4, 5, 6, 9]


## sort in NumPy array

In [192]:
import numpy as np
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
arr = np.sort(arr)
print(arr)  # Output: [1 1 2 3 4 5 6 9]


[1 1 2 3 4 5 6 9]


# How to find the maximum and minimum element in an array

## in list 

In [196]:
arr = [10, 20, 30, 40, 50]
print(max(arr))  # Output: 50
print(min(arr))  # Output: 10


50
10


## in Numpy 

In [199]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(np.max(arr))  # Output: 50
print(np.min(arr))  # Output: 10


50
10


# sum( list and Numpy)

In [203]:
arr = [1, 2, 3, 4, 5]
print(sum(arr))  # Output: 15


15


# How to find the index of an element?

In [206]:
arr = [10, 20, 30, 40]
print(arr.index(30)) 

2


In [208]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(np.where(arr == 30))  # Output: (array([2]),)


(array([2], dtype=int64),)


# How to input array 

In [4]:
import numpy as np

# Taking space-separated input from the user
arr = np.array(list(map(int, input("Enter numbers: ").split())))

print("NumPy Array:", arr)


Enter numbers:  2 3 4 6 7 7 8  3 4 5 


NumPy Array: [2 3 4 6 7 7 8 3 4 5]


In [38]:
import numpy as np

rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

matrix = []
for _ in range(rows):
    row = list(map(int, input().split()))  # Input row elements
    matrix.append(row)

arr = np.array(matrix)
print("NumPy Matrix:\n", arr)


Enter number of rows:  2
Enter number of columns:  1
 5
 6


NumPy Matrix:
 [[5]
 [6]]


In [61]:
# using numpy.fromstring()
import numpy as np
arr = np.fromstring(input("enter numbers: "), dtype=int, sep = ', ')
print(arr)

enter numbers:  3,4,5,6,7,8,10,11


[ 3  4  5  6  7  8 10 11]


In [44]:
#using numpy.reshape()
rows, cols = 2,3
arr = np.array(list(map(int, input("enter an list: ").split()))).reshape(rows, cols)
print(arr)

# Basic Input (split())	1D array (single row)
# Loop for Matrix Input	2D array (row by row input)
# numpy.fromstring()	Fast 1D array input
# reshape()	Convert flat input into multi-dimensional array
# Loop + reshape()	For 3D or complex arrays

enter an list:  2 3 4 5 6 7


[[2 3 4]
 [5 6 7]]


# map, reduce, filter 

## map 

In [13]:
#The map() function applies a given function to all items in an iterable (e.g., list, tuple) and returns a map object
#(an iterator).
#map(function, iterable)
def squares(n): 
    return n*n 
numbers = [2,4,5,1,3,5]
squared_numbers = map(squares, numbers)
print(list(squared_numbers))


[4, 16, 25, 1, 9, 25]


### Using Lambda Function 

In [20]:
numbers = [2,4,5,1,3,5]
squared = map(lambda x: x*x , numbers)
print(list(squared))

[4, 16, 25, 1, 9, 25]


## filter

In [25]:
# The filter() function filters elements from an iterable based on a condition
#filter(function, iterable)
def even_num(n): 
    return n%2==0
numbers =  [2,4,5,1,3,5]
even = filter(even_num, numbers)
print(list(even))

[2, 4]


## Reduce 

In [30]:
#The reduce() function applies a function cumulatively to the items of an iterable.
#It is part of the functools module.
#from functools import reduce
#reduce(function, iterable)
from functools import reduce 
def add(x,y):
    return x+y
numbers = [2,4,5,6,1]    
sum = reduce(add, numbers)
print(sum)

18


# Find the Second Largest Element in an Array

In [5]:
def second_largest(arr): # time complexity : O(N)
    first = second = float('-inf')
    for num in arr: 
        if num >first: 
            second = first
            first = num 
        elif num>second: 
            second = num 
    return second if second != float('-inf') else None 
arr = [10,2,4,5,6]    
print(second_largest(arr))

6


# Reverse an Array Without Extra Space

In [60]:
def reverse_array(arr): 
    left, right = 0, len(arr)-1 
    while left<right: 
        arr[left], arr[right]= arr[right], arr[left]
        left+=1
        right-=1
    return arr
arr = [1,3,4,5,3,7]
print(reverse_array(arr))

[7, 3, 5, 4, 3, 1]


# Check If an Array Is Sorted

In [69]:
def is_sorted(arr): 
    for i in range(len(arr)-1): 
        if arr[i]> arr[i+1]: 
            return False
    return True    
arr = list(map(int, input("enter an list: ").split()))
is_sorted(arr)

enter an list:  3 4 5 3


False

#  Move Zeros to End (Without Changing Order)

In [1]:
def move_zeros(arr):
    non_zero_index = 0
    for i in range(len(arr)):
        if arr[i] != 0:
            arr[non_zero_index], arr[i] = arr[i], arr[non_zero_index]
            non_zero_index += 1
    return arr

# Example
arr = [0, 1, 0, 3, 12]
print(move_zeros(arr))  # Output: [1, 3, 12, 0, 0]


[1, 3, 12, 0, 0]


# wap to input positive integer & convert it into binary using arrays

In [13]:
n = 25
i = 0 
x = [0]* 20 
while n > 0: 
    x[i] = n%2
    n = n//2 #floor division" operator.
    i+=1
x = x[:i]  
x = x[::-1]
print(x)   

[1, 1, 0, 0, 1]


In [7]:
# without array 
n = 25 
i = 0 
s = 0 

while n>0:
    x = n%2
    n = n//2
    s = s+ x*(10**i)
    i+=1
print(s)    
    

11001


In [17]:
n = 25
binary_digits = []

while n > 0:
    remainder = n % 2
    binary_digits.append(remainder)
    n = n // 2
print(binary_digits)
binary_digits.reverse()
print("Binary representation:", binary_digits)

[1, 0, 0, 1, 1]
Binary representation: [1, 1, 0, 0, 1]


# Largest and Smallest Element

In [2]:
def get_max_min(arr): 
    return min(arr), max(arr)
arr = [3,4,5,6,7,8,10] 
print(get_max_min(arr))

(3, 10)


In [6]:
# iterable method (linear Search)
def get_max_min(arr): 
    if not arr: 
        return None, None
    max = arr[0] 
    min = arr[0]
    for num in arr: 
        if num > max: 
            max = num
        if num < min : 
            min = num 
    return min, max 
    
arr =   [3,4,5,6,7,8,10]  
print(get_max_min(arr))

(3, 10)


In [12]:
# Sorting Method
arr =   [3,4,5,6,7,8,10]  
arr.sort()
min = arr[0]
max = arr[-1]
print(min, max)

3 10


In [1]:
def find_max_min(arr, low, high):
    if low == high:
        # If there's only one element, it is both max and min
        return arr[low], arr[low]
    elif high == low + 1:
        # If there are two elements, compare them directly
        return (max(arr[low], arr[high]), min(arr[low], arr[high]))
    else:
        # Divide the array into two halves and recursively find max and min
        mid = (low + high) // 2
        max1, min1 = find_max_min(arr, low, mid)       # First half
        max2, min2 = find_max_min(arr, mid + 1, high)  # Second half
        return max(max1, max2), min(min1, min2)        # Combine results

# Example usage
arr = [3, 5, 1, 8, -2, 7]
max_val, min_val = find_max_min(arr, 0, len(arr) - 1)
print("Maximum:", max_val, "Minimum:", min_val)

Maximum: 8 Minimum: -2
