### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [1]:
import numpy as np 

In [8]:
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [16]:
# dtype
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [20]:
np.array([1,0,3],dtype = bool)

array([ True, False,  True])

In [22]:
np.array([1,2,3],dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [26]:
# np.arange
print(np.arange(1,11))
print(np.arange(1,11,2))

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [30]:
# with reshape
print(np.arange(1,11).reshape(5,2))
print(np.arange(1,11).reshape(2,5))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [34]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
# np.random
np.random.random((3,4))

array([[0.78269962, 0.21909392, 0.12506805, 0.30857019],
       [0.20299399, 0.3186546 , 0.34981605, 0.2860204 ],
       [0.64828655, 0.11959775, 0.67242217, 0.70806874]])

In [42]:
# np.linspace
np.linspace(-10,10,10)# generate numbers in equal distance 

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [44]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# array attributes

In [47]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [49]:
print(a1)# vector
print(a2)# matrix
print(a3)# tensor

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [51]:
# ndim
a1.ndim

1

In [53]:
a3.ndim

3

In [55]:
# shape
a1.shape

(10,)

In [57]:
a3.shape

(2, 2, 2)

In [61]:
 # size
print(a1.size)
print(a3.size)

10
8


In [65]:
# itemsize
print(a1.itemsize)
print(a3.itemsize)

4
4


In [71]:
# dtype
print(a1.dtype)
print(a2.dtype)

int32
float64


# changing datatype

In [80]:
# astype
a3.astype(np.float64)# memory optimization method

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

# array operations

In [83]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [85]:
# scalar operations
print(a1*2)# all operations works here 

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [91]:
# relational operators
print(a2>5)
print(a2>15)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [93]:
print(a2==15)

[[False False False  True]
 [False False False False]
 [False False False False]]


In [95]:
# vector operations (cuz it happening between two numpy arrays)
print(a1+a2)# all operatons i can use here 

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


# array functions


In [5]:
a1 = np.random.random((3,3))
a2 = np.round(a1*100)
print(a1)

[[0.61530536 0.93306134 0.75454714]
 [0.95368808 0.03208922 0.42486436]
 [0.51687813 0.48053391 0.91635205]]


In [7]:
np.max(a1)

0.9536880820928237

In [11]:
np.min(a1)

0.03208922227054989

In [13]:
np.prod(a1)

0.0012819694284582125

In [15]:
np.sum(a1)

5.6273195892456584

In [17]:
np.max(a1,axis = 0)

array([0.95368808, 0.93306134, 0.91635205])

In [21]:
np.min(a1,axis = 0) # 0 -> for column, 1-> for row

array([0.51687813, 0.03208922, 0.42486436])

In [23]:
np.max(a1,axis = 1)

array([0.93306134, 0.95368808, 0.91635205])

In [25]:
np.min(a1,axis = 1)

array([0.61530536, 0.03208922, 0.48053391])

In [27]:
np.sum(a1,axis = 0)

array([2.08587157, 1.44568447, 2.09576355])

In [29]:
np.prod(a1,axis = 0)

array([0.30330894, 0.01438777, 0.29376431])

In [31]:
np.mean(a1,axis = 0)

array([0.69529052, 0.48189482, 0.69858785])

In [33]:
np.median(a1,axis = 0)

array([0.61530536, 0.48053391, 0.75454714])

In [35]:
np.std(a1,axis = 0)

array([0.18708101, 0.36782158, 0.20451344])

In [37]:
np.var(a1,axis = 0)

array([0.0349993 , 0.13529272, 0.04182575])

In [39]:
# trigonometric functions 
np.sin(a1)

array([[0.57720791, 0.80344635, 0.68495879],
       [0.81555526, 0.03208372, 0.4121972 ],
       [0.4941685 , 0.46225269, 0.79338633]])

In [45]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [47]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [49]:
 np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [51]:
# log and exponents
np.exp(a1)

array([[1.8502215 , 2.54228005, 2.12664823],
       [2.59526358, 1.03260963, 1.52938296],
       [1.67678476, 1.61693747, 2.50015331]])

In [55]:
# round/floor/ceil
np.round(np.random.random((2,3))*100)

array([[95., 23., 98.],
       [35., 83., 58.]])

In [57]:
np.floor(np.random.random((2,3))*100)

array([[95., 11., 53.],
       [65., 75.,  1.]])

# indexing and slicing 

In [60]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [62]:
a1 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a1[-1]

9

In [68]:
a1[1]

1

In [70]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
a2[1,2]

6

In [78]:
a2[1][2]

6

In [80]:
a3 

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [84]:
a3[0][1][0]

2

In [86]:
a3[0,1,0]

2

In [88]:
a1[2:5]

array([2, 3, 4])

In [90]:
a2[0,:]# first row


array([0, 1, 2, 3])

In [92]:
a2[:,2]# third column

array([ 2,  6, 10])

In [94]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [96]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [98]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [104]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [106]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [110]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [112]:
a3[1:2]

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [114]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [116]:
a3[0,1,:]

array([3, 4, 5])

In [118]:
a3[0,2,:]

array([6, 7, 8])

In [122]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [126]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [132]:
a3[0::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [134]:
# iterating
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [136]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [138]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [140]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# reshaping

In [143]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [147]:
a2.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [149]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [153]:
# raval 
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [155]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# stacking 

In [162]:
# horizontal stacking 
# shape must be same
b = np.arange(12).reshape(3,4)
b1 = np.arange(12,24).reshape(3,4)
np.hstack((b,b1))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [164]:
np.hstack((b,b1,b))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [168]:
# vertical stacking
np.vstack((b,b1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Spliting 

In [175]:
# horizontal spliting 
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [183]:
np.hsplit(b,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [187]:
np.hsplit(b,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [189]:
np.vsplit(b,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]