### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [4]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([56, 49, 20,  7, 52,  7, 95, 11, 44, 11, 54, 52, 91,  5, 57])

In [8]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[27, 49, 28, 69],
       [93, 87, 27, 12],
       [ 2, 62, 57, 30],
       [82, 69, 47, 43],
       [68, 72, 63,  6],
       [32, 54, 93, 11]])

In [10]:
np.sort(a)

array([ 5,  7,  7, 11, 11, 20, 44, 49, 52, 52, 54, 56, 57, 91, 95])

In [12]:
np.sort(b)

array([[27, 28, 49, 69],
       [12, 27, 87, 93],
       [ 2, 30, 57, 62],
       [43, 47, 69, 82],
       [ 6, 63, 68, 72],
       [11, 32, 54, 93]])

In [14]:
np.sort(b,axis = 0)# column vise sorting

array([[ 2, 49, 27,  6],
       [27, 54, 28, 11],
       [32, 62, 47, 12],
       [68, 69, 57, 30],
       [82, 72, 63, 43],
       [93, 87, 93, 69]])

In [16]:
np.sort(a)[::-1]# sorting in decending order 

array([95, 91, 57, 56, 54, 52, 52, 49, 44, 20, 11, 11,  7,  7,  5])

In [24]:
np.sort(b, axis = 1)[::-1]

array([[11, 32, 54, 93],
       [ 6, 63, 68, 72],
       [43, 47, 69, 82],
       [ 2, 30, 57, 62],
       [12, 27, 87, 93],
       [27, 28, 49, 69]])

In [20]:
np.sort(b,axis = 0)[::-1]

array([[93, 87, 93, 69],
       [82, 72, 63, 43],
       [68, 69, 57, 30],
       [32, 62, 47, 12],
       [27, 54, 28, 11],
       [ 2, 49, 27,  6]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [27]:
np.append(a,200)

array([ 56,  49,  20,   7,  52,   7,  95,  11,  44,  11,  54,  52,  91,
         5,  57, 200])

In [33]:
np.append(b,np.ones((b.shape[0],1)))

array([27., 49., 28., 69., 93., 87., 27., 12.,  2., 62., 57., 30., 82.,
       69., 47., 43., 68., 72., 63.,  6., 32., 54., 93., 11.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [35]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[27., 49., 28., 69.,  1.],
       [93., 87., 27., 12.,  1.],
       [ 2., 62., 57., 30.,  1.],
       [82., 69., 47., 43.,  1.],
       [68., 72., 63.,  6.,  1.],
       [32., 54., 93., 11.,  1.]])

In [41]:
np.append(b,np.random.random((b.shape[0],1)),axis = 1)

array([[2.70000000e+01, 4.90000000e+01, 2.80000000e+01, 6.90000000e+01,
        6.08109949e-01],
       [9.30000000e+01, 8.70000000e+01, 2.70000000e+01, 1.20000000e+01,
        5.29391912e-01],
       [2.00000000e+00, 6.20000000e+01, 5.70000000e+01, 3.00000000e+01,
        8.75789767e-02],
       [8.20000000e+01, 6.90000000e+01, 4.70000000e+01, 4.30000000e+01,
        9.72070768e-01],
       [6.80000000e+01, 7.20000000e+01, 6.30000000e+01, 6.00000000e+00,
        8.49255798e-01],
       [3.20000000e+01, 5.40000000e+01, 9.30000000e+01, 1.10000000e+01,
        1.46264567e-01]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [50]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [54]:
np.concatenate((c,d), axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [56]:
np.concatenate((c,d),axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [63]:
e = np.array([1,1,1,2,3,4,4,3,3,233,4,33,3,2,3,3,44])
np.unique(e)

array([  1,   2,   3,   4,  33,  44, 233])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [70]:
a

array([56, 49, 20,  7, 52,  7, 95, 11, 44, 11, 54, 52, 91,  5, 57])

In [72]:
a.shape

(15,)

In [68]:
np.expand_dims(a,axis=0)

array([[56, 49, 20,  7, 52,  7, 95, 11, 44, 11, 54, 52, 91,  5, 57]])

In [74]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [78]:
np.expand_dims(a,axis=1)

array([[56],
       [49],
       [20],
       [ 7],
       [52],
       [ 7],
       [95],
       [11],
       [44],
       [11],
       [54],
       [52],
       [91],
       [ 5],
       [57]])

In [80]:
np.expand_dims(a,axis=1).shape

(15, 1)

  ### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [83]:
np.where(a>50)

(array([ 0,  4,  6, 10, 11, 12, 14], dtype=int64),)

In [87]:
# replace all values > 50 with 0 
np.where(a>50,0,a)

array([ 0, 49, 20,  7,  0,  7,  0, 11, 44, 11,  0,  0,  0,  5,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [90]:
np.argmax(a) 

6

In [92]:
a

array([56, 49, 20,  7, 52,  7, 95, 11, 44, 11, 54, 52, 91,  5, 57])

In [94]:
b

array([[27, 49, 28, 69],
       [93, 87, 27, 12],
       [ 2, 62, 57, 30],
       [82, 69, 47, 43],
       [68, 72, 63,  6],
       [32, 54, 93, 11]])

In [98]:
np.argmax(b,axis=0)

array([1, 1, 5, 0], dtype=int64)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [102]:
a

array([56, 49, 20,  7, 52,  7, 95, 11, 44, 11, 54, 52, 91,  5, 57])

In [106]:
np.cumsum(a)

array([ 56, 105, 125, 132, 184, 191, 286, 297, 341, 352, 406, 458, 549,
       554, 611])

In [108]:
b

array([[27, 49, 28, 69],
       [93, 87, 27, 12],
       [ 2, 62, 57, 30],
       [82, 69, 47, 43],
       [68, 72, 63,  6],
       [32, 54, 93, 11]])

In [110]:
np.cumsum(b)

array([  27,   76,  104,  173,  266,  353,  380,  392,  394,  456,  513,
        543,  625,  694,  741,  784,  852,  924,  987,  993, 1025, 1079,
       1172, 1183])

In [112]:
np.cumsum(b,axis=0)

array([[ 27,  49,  28,  69],
       [120, 136,  55,  81],
       [122, 198, 112, 111],
       [204, 267, 159, 154],
       [272, 339, 222, 160],
       [304, 393, 315, 171]])

In [114]:
np.cumsum(b,axis = 1)

array([[ 27,  76, 104, 173],
       [ 93, 180, 207, 219],
       [  2,  64, 121, 151],
       [ 82, 151, 198, 241],
       [ 68, 140, 203, 209],
       [ 32,  86, 179, 190]])

 ### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html